name: OSV-Scanner with Auto Fix

on:
  push:
    branches: [ "main" ]

permissions:
  security-events: write
  contents: write  # Allow committing and pushing changes

jobs:
  scan-scheduled:
    name: Run OSV Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Run OSV Scanner
        id: os-scanner
        uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@1f1242919d8a60496dd1874b24b62b2370ed4c78" # Reference reusable workflow
        with:
          scan-args: |-
            -r
            --skip-git
            ./
        continue-on-error: true  # Let the workflow proceed even if this step fails

      - name: Set Scan Result Output
        run: echo "vulnerabilities_found=${{ steps.os-scanner.outcome }}" >> $GITHUB_ENV

  npm-audit-fix:
    name: Run npm audit fix and Create PR
    runs-on: ubuntu-latest
    needs: scan-scheduled
    if: ${{ env.vulnerabilities_found == 'failure' }}  # Run only if vulnerabilities were found
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm install

      - name: Run npm audit fix
        run: npm audit fix || echo "No vulnerabilities to fix"

      # - name: Commit and Push Changes
      #   run: |
      #     git config user.name "GitHub Actions Bot"
      #     git config user.email "actions@github.com"
      #     git checkout -b npm-audit-fix-branch
      #     git add package-lock.json package.json
      #     git commit -m "Fix vulnerabilities using npm audit fix"
      #     git push origin npm-audit-fix-branch

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: npm-audit-fix
