name: OSV-Scanner with Auto Fix

on:
  push:
    branches: ["main"]
      

permissions: {}
#   # Required permissions for the workflow
#   security-events: write
#  contents: write  # Needed for committing and pushing changes

jobs:
  osv-scan:
    permissions:
      contents: read # to fetch code (actions/checkout)
      security-events: write # for uploading SARIF files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'    

      - name: "Run scanner"
        id: run-scanner
        uses: google/osv-scanner/actions/scanner@main
        with:
          scan-args: |-
            --recursive
            --skip-git=true
            ./
        continue-on-error: true

      - name: Capture Scan Result
        if: always()
        run: |
          if [ "${{ steps.run-scanner.outcome }}" == "success" ]; then
            echo "scan-result=pass" >> $GITHUB_ENV
          else
            echo "scan-result=fail" >> $GITHUB_ENV
          fi      

      # - name: Show Scan Result
      #   run: |
      #     echo "Scan Result: ${{ env.scan-result }}"        

      # - name: Check Scan Result
      #   run: |
      #     if [ "${{ env.scan-result }}" == "fail" ]; then
      #       echo "Vulnerabilities found."
      #       cd client  # Ensure this directory exists, or change to the correct directory
      #       ls -la
      #       npm install
      #       npm audit fix --force
      #       git config --global user.name "arunodhayamsam"
      #       git config --global user.email "100224916+arunodhayamsam@users.noreply.github.com"
      #       git checkout -b feature/npm-audit-fix-branch
      #       git status
      #       git add package-lock.json package.json
      #       git commit -m "Fix vulnerabilities using npm audit fix"
      #       git push origin feature/npm-audit-fix-branch -f
      #     else
      #       echo "No Vulnerabilities"  
      #     fi   

      # - name: Commit and Push Changes
      #   run: |

  npm-audit-fix:
    name: Run npm audit fix and Create PR
    runs-on: ubuntu-latest
    needs: osv-scan
    steps:
      - name: Check Scan Result
        run: |
          if [ "${{ env.scan-result }}" != "fail" ]; then
            echo "No vulnerabilities found. Skipping npm audit fix."
            exit 0
          fi

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: |
          cd client
          npm install

      - name: Run npm audit fix
        run: npm audit fix --force

      - name: Commit and Push Changes
        run: |
          git config user.name "arunodhayamsam"
          git config user.email "100224916+arunodhayamsam@users.noreply.github.com"
          git status
          git checkout -b npm-audit-fix-branch
          git add package-lock.json package.json
          git commit -m "Fix vulnerabilities using npm audit fix"
          git push origin npm-audit-fix-branch      
              
        # continue-on-error: true  

      # - name: "Run osv-scanner-reporter"
      #   uses: google/osv-scanner/actions/reporter@main
      #   with:
      #     scan-args: |-
      #       --output=results.sarif
      #       --new=results.json
      #       --gh-annotations=false 
      #   continue-on-error: true 

      # - name: Check
      #   run: echo "run or not"     
