name: OSV-Scanner with Auto Fix

on:
  push:
    branches: [ "main" ]

permissions:
  security-events: write
  contents: write  # Allow committing and pushing changes

jobs:
  scan-scheduled:
    name: Run OSV Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Run OSV Scanner
        id: osv-scan
        uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@1f1242919d8a60496dd1874b24b62b2370ed4c78
        with:
          scan-args: |-
            -r
            --skip-git
            ./
      - name: Check OSV Scanner Results
        id: check-results
        run: |
          if [ "${{ steps.osv-scan.outcome }}" != "success" ]; then
            echo "Vulnerabilities found. Triggering npm audit fix..."
            echo "fail" > osv-result.txt
          else
            echo "pass" > osv-result.txt
          fi
      - name: Upload OSV Scan Result
        uses: actions/upload-artifact@v3
        with:
          name: osv-result
          path: osv-result.txt

  npm-audit-fix:
    name: Run npm audit fix and Create PR
    runs-on: ubuntu-latest
    needs: scan-scheduled
    steps:
      - name: Download OSV Scan Result
        uses: actions/download-artifact@v3
        with:
          name: osv-result
      - name: Run npm audit fix if vulnerabilities found
        if: ${{ hashFiles('osv-result.txt') == hashFiles('<<REPO>>/fail.txt') }}
        run: echo "run npm audit"
          
