name: OSV-Scanner with Auto Fix

on:  
  workflow_dispatch:  

inputs:
  targetbranch:
    description: Provide the pr raised branch
    type: string
    default: ""
  newfixbranch:
    description: Provide the branch to make the correction
    type: string
    default: "bugfix/"


permissions: 
  contents: write
  security-events: write

jobs:
  npm-audit-fix:
    permissions:
      contents: write
      security-events: write
    name: Run npm audit fix and Create PR
    runs-on: ubuntu-latest
    steps:
      
      - name: Print output value
        run: |
          echo "scan result is failed"
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.targetbranch }}
      - name: Set up Node.js  
        uses: actions/setup-node@v3
        with:
           node-version: 'lts/*'
      - name: Install Dependencies on client
        run: |
          ls -la
          git branch
          cd client
          npm install 
          npm audit fix --force
      - name: Install Dependencies on server
        run: |
          ls -la
          cd server
          npm install 
          npm audit fix --force    
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: Finding the vulnerabilities
          branch: ${{ inputs.newfixbranch }}
          base: ${{ inputs.targetbranch }}
          # title: 'Fix vulnerabilities in ${{ steps.get-source-branch.outputs.source-branch }}'
          body: |
            This PR was created automatically to fix vulnerabilities detected during the scan. 

      