name: OSV-Scanner to find vulnerabilities
on:
  pull_request:
    branches:
      - main
      - develop  
  workflow_dispatch:    

permissions: 
  contents: write
  security-events: write

jobs:
  osv-scan:
    permissions:
      contents: write
      security-events: write # for uploading SARIF files
    runs-on: ubuntu-latest
    outputs:
      scan-result: ${{ steps.set-scan-result.outputs.scan-result }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Instll Dependencies
        run: |
          cd client
          npm install
      - name: "Run scanner"
        id: run-scanner
        uses: google/osv-scanner/actions/scanner@main
        with:
          scan-args: |-
            --config=.github/config.toml
            -r
            ./
        
