name: OSV-Scanner with Auto Fix

on:  
  workflow_dispatch:
    inputs:
      targetbranch:
        description: Provide the PR raised branch
        type: string
        default: ""
      newfixbranch:
        description: Provide the branch to make the correction
        type: string
        default: "bugfix/"

permissions: 
  contents: write
  security-events: write

jobs:
  npm-audit-fix:
    permissions:
      contents: write
      security-events: write
    name: Run npm audit fix and Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Print output value
        run: |
          echo "scan result is failed"
      
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.targetbranch }}
      
      - name: Set up Node.js  
        uses: actions/setup-node@v3
        with:
           node-version: 'lts/*'
      
      - name: Install Dependencies on client
        run: |
          ls -la
          git branch
          cd client
          npm install 
          npm audit fix --force
      
      - name: Install Dependencies on server
        run: |
          ls -la
          cd server
          npm install 
          npm audit fix --force 

      - name: Commit and Push Changes
        run: |
           git config user.name "arunodhayamsam"
           git config user.email "100224916+arunodhayamsam@users.noreply.github.com"
           git status
           git checkout -b ${{ inputs.newfixbranch }}
           git status
           git add .
           git commit -m "Fix vulnerabilities using npm audit fix"
           git push https://arunodhayamsam:${{ secrets.GH_TOKEN }}@github.com/arunodhayamsam/Whisper.git ${{ inputs.newfixbranch }}       

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: Fix vulnerabilities using npm audit fix
          branch: ${{ inputs.newfixbranch }}
          base: ${{ inputs.targetbranch }}
          body: |
            This PR was created automatically to fix vulnerabilities detected during the scan. 
