name: OSV-Scanner with Auto Fix

on:
  pull_request:
    branches:
      - main
      - develop  
  workflow_dispatch:    

permissions: 
  contents: write
  security-events: write

jobs:
  osv-scan:
    permissions:
      contents: write
      security-events: write # for uploading SARIF files
    runs-on: ubuntu-latest
    outputs:
      scan-result: ${{ steps.set-scan-result.outputs.scan-result }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: "Run scanner"
        id: run-scanner
        uses: google/osv-scanner-action/osv-scanner-action@f8115f2f28022984d4e8070d2f0f85abcf6f3458
        with:
          scan-args: |-
            --skip-git
            --recursive
            ./
        continue-on-error: true
      - name: Capture Scan Result
        id: set-scan-result
        run: |
          if [ "${{ steps.run-scanner.outcome }}" == "success" ]; then
            echo "scan-result=pass" >> $GITHUB_ENV
            echo "::set-output name=scan-result::pass"
          else
            echo "scan-result=fail" >> $GITHUB_ENV
            echo "::set-output name=scan-result::fail"
          fi

  npm-audit-fix:
    permissions:
      contents: write
      security-events: write
    name: Run npm audit fix and Create PR
    runs-on: ubuntu-latest
    needs: osv-scan
    if: needs.osv-scan.outputs.scan-result == 'fail'
    steps:
      
      - name: Print output value
        run: |
          echo "scan result is failed"
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Node.js  
        uses: actions/setup-node@v3
        with:
           node-version: 'lts/*'
      - name: Install Dependencies on client
        run: |
          ls -la
          cd client
          npm install 
          npm audit fix --force
      - name: Install Dependencies on server
        run: |
          ls -la
          cd server
          npm install 
          npm audit fix --force    
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: Finding the vulnerabilities
          branch: feature/example-patches 
          base: ${{ github.head_ref }}
          title: 'Fix vulnerabilities in ${{ steps.get-source-branch.outputs.source-branch }}'
          body: |
            This PR was created automatically to fix vulnerabilities detected during the scan. 

      