name: Go Release Process

on:
  push:
    branches:
      - "main" # triggers only if a new version tag is pushed, like `0.8.4` or else

# permissions:
#   # Adjusting the permissions for calling a reusable workflow
#   actions: none  # Change this to 'none' for reusable workflows
#   contents: none  # Change this to 'none' for reusable workflows
#   security-events: write  # Keep this as write since we are uploading SARIF for security

jobs:
  osv-scan:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v1.9.2"
    with:
      # Scan the top-level package-lock.json and package.json files
      scan-args: |-
        --recursive
        --skip-git
        ./
